### ISSUE TITLE
Module says I am 0 years old today?

### ISSUE THREAD

**Issue by BerkSmash1984** [amitchone/MMM-birthdays#7]
My birthday is on 11/16/1984. I have this module installed with the below configuration: 
![image](https://github.com/amitchone/MMM-birthdays/assets/104693081/156dbcf6-e7d4-4a0f-93db-36d2f643154f)

My MM is displaying the following:
![image](https://github.com/amitchone/MMM-birthdays/assets/104693081/3d15440e-df8c-4e27-9da3-dcc5256365e5)

Any thoughts?

**Comment by amitchone** [comment]
Hey, cheers for getting in touch.

Looks like you've got a typo - it says `dbo` rather than `dob` for the problematic entry! Fingers crossed that does the trick and it's not something else underlying. It's an interesting test case though, so when I get a chance I will double-check the behaviour when a date of birth isn't supplied.

Hope this helps,
Adam

**Comment by BerkSmash1984** [comment]
Well shoot, that was it! Sorry for the oversight and thanks for the help!

**Comment by BerkSmash1984** [comment]
Had typo in my config :)
